---
- hosts: usweb.all
  vars:
    owner: ubuntu
    group: ubuntu
  tasks:
    - name: create nginx content structure
      file:
        path: /home/ubuntu/share/nginx/html
        state: directory
        owner: "{{ owner }}"
        group: "{{ group }}"
    - name: copy nginx error page
      copy:
        src: ../../shared/nginx/html/50x.html
        dest: /home/ubuntu/share/nginx/html/50x.html
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: 0644
      # notify:
      #   - restart nginx
    - name: copy main nginx config
      copy:
        src: ../nginx/nginx.conf
        dest: /home/ubuntu/etc/nginx/nginx.conf
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: 0644
    - name: copy main nginx config
      copy:
        src: ../nginx/ssl.conf
        dest: /home/ubuntu/etc/nginx/ssl.conf
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: 0644
      # notify:
      #   - restart nginx
    - name: copy nginx config
      copy:
        src: ../nginx/conf.d
        dest: /home/ubuntu/etc/nginx/
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: 0644
      # notify:
      #   - restart nginx
    - name: copy ssh authorized keys
      copy:
        src: ../authorized_keys
        dest: /home/ubuntu/.ssh/authorized_keys
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: 0600

    - name: copy us2proxy upstart config
      copy:
        src: ../init/us2proxy.conf
        dest: /etc/init/us2proxy.conf
        owner: "root"
        group: "root"
        mode: 0644

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
